
name: Bug Report
description: Report a problem with the SatCom Forecast integration.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting a bug! Please fill out the following:"
  - type: input
    id: environment
    attributes:
      label: Home Assistant version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      render: shell
