
name: Feature Request
description: Suggest a new feature or enhancement.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "Have a feature idea? We'd love to hear it."
  - type: textarea
    id: feature
    attributes:
      label: What would you like to see?
    validations:
      required: true
